import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';
import {
  NOT_FOUND_YEAR_TOKEN,
  packNotFoundHtml,
  renderNotFoundDocumentHtml,
} from './notFoundDocument.ts';

const BEGIN = '/* NOT_FOUND_HTML_BEGIN */';
const END = '/* NOT_FOUND_HTML_END */';

const target = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  '../../../infra/lib/cloudfront/viewer-response-function.js',
);

/** ASCII-only source; the runtime string is unchanged. */
const jsString = (value: string): string =>
  JSON.stringify(value).replace(
    /[^\x20-\x7e]/g,
    (ch) => `\\u${ch.charCodeAt(0).toString(16).padStart(4, '0')}`,
  );

const source = fs.readFileSync(target, 'utf8');
const begin = source.indexOf(BEGIN);
const end = source.indexOf(END);
if (begin === -1 || end < begin) {
  throw new Error(`Missing ${BEGIN} / ${END} in ${target}`);
}
const { dict, packed } = packNotFoundHtml(renderNotFoundDocumentHtml());
const block = `${BEGIN}
// Generated by npm run not-found:generate - do not edit by hand.
var NOT_FOUND_YEAR = ${jsString(NOT_FOUND_YEAR_TOKEN)};
var NOT_FOUND_DICT = [${dict.map(jsString).join(',')}];
var NOT_FOUND_HTML = ${jsString(packed)};
${END}`;
const next = await prettier.format(
  source.slice(0, begin) + block + source.slice(end + END.length),
  { ...(await prettier.resolveConfig(target)), filepath: target },
);
fs.writeFileSync(target, next);
console.log(
  `viewer-response-function.js: ${Buffer.byteLength(next)} bytes (CloudFront limit 10240)`,
);
