/**
 * Generated by services/publisher/scripts/generate-publish-surface.ts — do not edit by hand.
 * Source: publisher target `adminMutationPrefixes` / `adminSoftDelete`.
 */
export const PUBLISH_ADMIN_MUTATION_PREFIXES = [
  '/api/admin/home',
  '/api/admin/posts',
  '/api/admin/resume',
] as const;

export const PUBLISH_ADMIN_SOFT_DELETE_PREFIXES = ['/api/admin/posts'] as const;
