export { AppApiProvider, useGetApiClient } from './AppApiProvider.js';
export {
  defaultTimers,
  type ConfirmFn,
  type RetrySignals,
  type Timers,
} from './platform.js';
export { mergeEditorSeo } from './mergeEditorSeo.js';
export { clearPendingFlushes, hasPendingFlushes } from './pendingFlushes.js';
export {
  useQueuedAutosave,
  type AutosaveResult,
  type FlushResult,
  type SaveState,
} from './useQueuedAutosave.js';
export {
  useDraftPublishEditor,
  type DraftPublishAutosave,
  type DraftPublishDeleteOptions,
  type DraftPublishEditorOptions,
  type DraftPublishHold,
} from './useDraftPublishEditor.js';
export {
  useVersionedDocEditor,
  type VersionedDocDeleteOptions,
  type VersionedDocEditorOptions,
  type VersionedDocEntity,
} from './useVersionedDocEditor.js';
export {
  useVersionedEntityEditor,
  type VersionedEditorEntity,
  type VersionedEntityActionBarProps,
  type VersionedEntityEditorOptions,
} from './useVersionedEntityEditor.js';

export { queryKeys } from './query/keys.js';
export {
  ApiError,
  asMutateResult,
  completeTask,
  createNote,
  createPost,
  createProject,
  createTask,
  deleteNote,
  deletePost,
  deleteProject,
  deleteTask,
  discardHome,
  discardPost,
  discardProject,
  discardResume,
  fetchDailyNote,
  fetchHome,
  fetchNote,
  fetchNotesPage,
  fetchPost,
  fetchPosts,
  fetchPostsPage,
  fetchProject,
  fetchProjects,
  fetchResume,
  fetchTask,
  fetchTasksPage,
  isEmptyDailyNote,
  publishHome,
  publishPost,
  publishProject,
  publishResume,
  reopenTask,
  searchNotebook,
  unpublishHome,
  unpublishPost,
  unpublishProject,
  unpublishResume,
  unwrap,
  updateHome,
  updateNote,
  updatePost,
  updateProject,
  updateResume,
  updateTask,
  upsertDailyNote,
  type CreateNoteRequest,
  type CreatePostRequest,
  type CreateProjectRequest,
  type CreateTaskRequest,
  type DailyNoteGetResponse,
  type EmptyDailyNote,
  type ExpectedVersionRequest,
  type Home,
  type ListNotesQuery,
  type ListTasksQuery,
  type MutateResult,
  type Note,
  type NotebookArea,
  type NotebookSearchQuery,
  type NotebookSearchResponse,
  type NoteType,
  type NotesPage,
  type Post,
  type Project,
  type Resume,
  type Task,
  type TasksPage,
  type UpdateHomeRequest,
  type UpdateNoteRequest,
  type UpdatePostRequest,
  type UpdateProjectRequest,
  type UpdateResumeRequest,
  type UpdateTaskRequest,
  type UpsertDailyNoteRequest,
} from './query/api.js';
export {
  preferNewerByVersion,
  setCachedHome,
  setCachedNote,
  setCachedPost,
  setCachedProject,
  setCachedResume,
  setCachedTask,
} from './query/cache.js';
export {
  createVersionedResource,
  type VersionedEntity,
  type VersionedResource,
  type VersionedResourceConfig,
} from './query/createVersionedResource.js';
export {
  createDraftPublishResource,
  type DraftPublishLifecycleMutators,
  type DraftPublishResource,
  type DraftPublishResourceConfig,
} from './query/createDraftPublishResource.js';
export {
  optimisticMutationHandlers,
  type OptimisticContext,
  type OptimisticTarget,
} from './query/optimistic.js';
export {
  postResource,
  useCreatePostMutation,
  useDeletePostMutation,
  usePostsQuery,
  useSetPostCache,
  type PostResourceParams,
} from './query/posts.js';
export {
  createStarterProjects,
  newProjectRequest,
  projectResource,
  STARTER_PROJECTS,
  useCreateProjectMutation,
  useCreateStarterProjectsMutation,
  useDeleteProjectMutation,
  useProjectsQuery,
  useSetProjectCache,
  type NewProjectInput,
  type ProjectResourceParams,
  type StarterProjectsResult,
} from './query/projects.js';
export {
  homeResource,
  useSetHomeCache,
  type HomeResourceParams,
} from './query/home.js';
export {
  resumeResource,
  useResumeQuery,
  useSetResumeCache,
  type ResumeResourceParams,
} from './query/resume.js';
export {
  dailyNoteResource,
  emptyDailyPlaceholder,
  fetchDailyNoteEntity,
  noteResource,
  useCreateNoteMutation,
  useDailyNoteDatesQuery,
  useDeleteNoteMutation,
  useNotesQuery,
  useSetNoteCache,
  type DailyNoteResourceParams,
  type NoteResourceParams,
} from './query/notes.js';
export {
  taskResource,
  useCompleteTaskMutation,
  useCreateTaskMutation,
  useDeleteTaskMutation,
  useReopenTaskMutation,
  useSetTaskCache,
  useTasksByIds,
  useTasksQuery,
  type TaskResourceParams,
  type TaskVersionVars,
} from './query/tasks.js';
export { useNotebookSearchQuery } from './query/search.js';
