import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  MAX_SLUG_LENGTH,
  POST_SLUG_KVS_SYNCED_KEY,
  PROJECT_SLUG_KVS_PREFIX,
  PROJECT_SLUG_KVS_SYNCED_KEY,
} from '@gagnechris/shared';
import { getPublishTargets } from '../src/publish-targets/registry.js';
import {
  STATIC_OPTION_B_PAGES,
  allOptionBPages,
  collectAdminMutationPrefixes,
  collectAdminSoftDeletePrefixes,
  collectS3OutputPatterns,
} from '../src/publish-targets/surface.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const targets = getPublishTargets();
const optionB = allOptionBPages(targets);
const adminPrefixes = collectAdminMutationPrefixes(targets);
const softDeletePrefixes = collectAdminSoftDeletePrefixes(targets);
const s3Outputs = collectS3OutputPatterns(targets);

const BEGIN = '/* PUBLISH_SURFACE_BEGIN */';
const END = '/* PUBLISH_SURFACE_END */';

function formatJsStringArray(values: readonly string[]): string {
  if (values.length === 0) return '[]';
  if (values.length === 1) return `['${values[0]}']`;
  return `[\n${values.map((v) => `  '${v}',`).join('\n')}\n]`;
}

function formatTsStringArray(values: readonly string[]): string {
  if (values.length === 0) return '[] as const';
  // Match Prettier: single-element arrays stay on one line.
  if (values.length === 1) return `['${values[0]}'] as const`;
  return `[\n${values.map((v) => `  '${v}',`).join('\n')}\n] as const`;
}

function updateViewerRequestFunction(): void {
  const path = join(root, 'infra/lib/cloudfront/viewer-request-function.js');
  const source = readFileSync(path, 'utf8');
  const beginIdx = source.indexOf(BEGIN);
  const endIdx = source.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Missing ${BEGIN} / ${END} markers in viewer-request-function.js`,
    );
  }
  const block = `${BEGIN}
// Generated by services/publisher/scripts/generate-publish-surface.ts — do not edit by hand.
// Publisher targets contribute optionBPaths; Vite static pages are listed in
// STATIC_OPTION_B_PAGES (services/publisher/src/publish-targets/surface.ts).
var OPTION_B_PAGES = ${formatJsStringArray(optionB)};

// KVS keys (packages/shared/src/slug-kvs.ts) and the slug cap (MAX_SLUG_LENGTH).
var BLOG_SYNCED_KEY = '${POST_SLUG_KVS_SYNCED_KEY}';
var PROJECT_KEY_PREFIX = '${PROJECT_SLUG_KVS_PREFIX}';
var PROJECTS_SYNCED_KEY = '${PROJECT_SLUG_KVS_SYNCED_KEY}';
var MAX_SLUG_LENGTH = ${MAX_SLUG_LENGTH};
${END}`;
  const next =
    source.slice(0, beginIdx) + block + source.slice(endIdx + END.length);
  writeFileSync(path, next);
}

function writeAdminRoutesGenerated(): void {
  const path = join(
    root,
    'packages/data/src/publish-admin-routes.generated.ts',
  );
  mkdirSync(dirname(path), { recursive: true });
  const body = `/**
 * Generated by services/publisher/scripts/generate-publish-surface.ts — do not edit by hand.
 * Source: publisher target \`adminMutationPrefixes\` / \`adminSoftDelete\`.
 */
export const PUBLISH_ADMIN_MUTATION_PREFIXES = ${formatTsStringArray(adminPrefixes)};

export const PUBLISH_ADMIN_SOFT_DELETE_PREFIXES = ${formatTsStringArray(softDeletePrefixes)};
`;
  writeFileSync(path, body);
}

/** One pattern per line; `#` lines are comments. */
const PUBLISHER_OWNED_PATHS_FILE =
  'scripts/publisher-owned-paths.generated.txt';

function writePublisherOwnedPaths(): void {
  const body = `# Generated by services/publisher/scripts/generate-publish-surface.ts — do not edit by hand.
# Every S3 key a publisher target writes (its \`s3Outputs\`), as aws s3 sync --exclude patterns.
# scripts/deploy-web.sh and scripts/local/seed-shell.sh keep these keys.
${s3Outputs.join('\n')}
`;
  writeFileSync(join(root, PUBLISHER_OWNED_PATHS_FILE), body);
}

updateViewerRequestFunction();
writeAdminRoutesGenerated();
writePublisherOwnedPaths();

console.log('publish-surface generated:');
console.log(`  Option B pages: ${optionB.join(', ')}`);
console.log(`  Static Vite pages: ${STATIC_OPTION_B_PAGES.join(', ')}`);
console.log(`  Admin mutation prefixes: ${adminPrefixes.join(', ')}`);
console.log(`  Admin soft-delete prefixes: ${softDeletePrefixes.join(', ')}`);
console.log(`  Publisher-owned S3 keys: ${s3Outputs.join(', ')}`);
