import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { getPublishTargets } from '../src/publish-targets/registry.js';
import {
  STATIC_OPTION_B_PREFIXES,
  allOptionBPrefixes,
  collectAdminMutationPrefixes,
  collectAdminSoftDeletePrefixes,
} from '../src/publish-targets/surface.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '../../..');
const targets = getPublishTargets();
const optionB = allOptionBPrefixes(targets);
const adminPrefixes = collectAdminMutationPrefixes(targets);
const softDeletePrefixes = collectAdminSoftDeletePrefixes(targets);

const BEGIN = '/* PUBLISH_SURFACE_BEGIN */';
const END = '/* PUBLISH_SURFACE_END */';

function formatJsStringArray(values: readonly string[]): string {
  if (values.length === 0) return '[]';
  if (values.length === 1) return `['${values[0]}']`;
  return `[\n${values.map((v) => `  '${v}',`).join('\n')}\n]`;
}

function formatTsStringArray(values: readonly string[]): string {
  if (values.length === 0) return '[] as const';
  // Match Prettier: single-element arrays stay on one line.
  if (values.length === 1) return `['${values[0]}'] as const`;
  return `[\n${values.map((v) => `  '${v}',`).join('\n')}\n] as const`;
}

function updateViewerRequestFunction(): void {
  const path = join(root, 'infra/lib/cloudfront/viewer-request-function.js');
  const source = readFileSync(path, 'utf8');
  const beginIdx = source.indexOf(BEGIN);
  const endIdx = source.indexOf(END);
  if (beginIdx === -1 || endIdx === -1 || endIdx < beginIdx) {
    throw new Error(
      `Missing ${BEGIN} / ${END} markers in viewer-request-function.js`,
    );
  }
  const block = `${BEGIN}
// Generated by services/publisher/scripts/generate-publish-surface.ts — do not edit by hand.
// Publisher targets contribute optionBPaths; Vite static pages are listed in
// STATIC_OPTION_B_PREFIXES (services/publisher/src/publish-targets/surface.ts).
var OPTION_B_PREFIXES = ${formatJsStringArray(optionB)};
${END}`;
  const next =
    source.slice(0, beginIdx) + block + source.slice(endIdx + END.length);
  writeFileSync(path, next);
}

function writeAdminRoutesGenerated(): void {
  const path = join(
    root,
    'packages/data/src/publish-admin-routes.generated.ts',
  );
  mkdirSync(dirname(path), { recursive: true });
  const body = `/**
 * Generated by services/publisher/scripts/generate-publish-surface.ts — do not edit by hand.
 * Source: publisher target \`adminMutationPrefixes\` / \`adminSoftDelete\`.
 */
export const PUBLISH_ADMIN_MUTATION_PREFIXES = ${formatTsStringArray(adminPrefixes)};

export const PUBLISH_ADMIN_SOFT_DELETE_PREFIXES = ${formatTsStringArray(softDeletePrefixes)};
`;
  writeFileSync(path, body);
}

updateViewerRequestFunction();
writeAdminRoutesGenerated();

console.log('publish-surface generated:');
console.log(`  Option B prefixes: ${optionB.join(', ')}`);
console.log(`  Static Vite pages: ${STATIC_OPTION_B_PREFIXES.join(', ')}`);
console.log(`  Admin mutation prefixes: ${adminPrefixes.join(', ')}`);
console.log(`  Admin soft-delete prefixes: ${softDeletePrefixes.join(', ')}`);
